# Generated by Django 5.2.9 on 2026-01-07 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('tax_rate', 'Tax Rate'), ('clustering', 'State Clustering')], max_length=20)),
                ('prediction_value', models.FloatField(help_text='Predicted tax rate or cluster number')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Full form input data')),
                ('confidence_interval', models.CharField(blank=True, help_text='Confidence or risk level', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
