# Generated by Django 5.2.8 on 2026-01-08 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Full form input data')),
                ('prediction_value', models.FloatField(help_text='Predicted value from regression model')),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence/R² score', null=True)),
                ('cluster_assigned', models.IntegerField(blank=True, help_text='Cluster assignment', null=True)),
                ('cluster_probability', models.FloatField(blank=True, help_text='Probability of cluster assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_regression_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Regression Prediction Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
