# Generated by Django 5.2.5 on 2026-01-04 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInsecurityPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_value', models.FloatField(help_text='Predicted food insecurity risk score (0-1)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Full form input data')),
                ('confidence', models.FloatField(default=0.0, help_text='Model confidence score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insecurity_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Insecurity Prediction',
                'verbose_name_plural': 'Food Insecurity Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
