# Generated by Django 5.2.6 on 2025-12-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('obesity', 'Obesity'), ('diabetes', 'Diabetes')], max_length=20)),
                ('prediction_value', models.FloatField(help_text='Predicted percentage')),
                ('risk_level_input', models.CharField(help_text='Risk Level input used', max_length=50)),
                ('confidence_interval', models.CharField(blank=True, help_text='CONFIDENCE INTERVAL STRING', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
