# Generated by Django 5.2.6 on 2025-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='input_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full form input data'),
        ),
    ]
