# Generated by Django 5.2.8 on 2026-01-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspredictionhistory',
            old_name='inputs',
            new_name='input_data',
        ),
        migrations.RenameField(
            model_name='accesspredictionhistory',
            old_name='prediction',
            new_name='prediction_value',
        ),
    ]
