# Generated by Django 5.2.9 on 2025-12-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ACCESS_INSECURITY_MANAGER', 'Access Insecurity Manager'), ('HEALTH_MANAGER', 'Health Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('LOCAL_ENVIRONMENT_MANAGER', 'Local Environment Manager')], help_text='User role determines access permissions', max_length=30),
        ),
    ]
